001 view job roles
MonikaKucinska/groupA-frontend pull request #4
Opened 2022-07-08 11:29 UTC by PatrykKiszelewski

2022-07-08 12:56 UTC, shaunganley requested changes

2022-07-08 12:56 UTC, shaunganley commented on app/controller/JobController.js
> +            data[i].role_name = `<td id = 'name${i+1}' class="govuk-table__cell">${data[i].role_name}</td>`
name we not do this loop in the view?

2022-07-08 12:56 UTC, shaunganley commented on test/unit/JobServiceTests.js
> +describe('JobService', function () {
need to add unit test for undefined and else blocks in service code

2022-07-11 10:42 UTC, shaunganley approved these changes

2022-07-11 10:42 UTC, shaunganley commented on app/controller/JobController.js
> +        res.locals.errormassege = e
I assume you'll want this to be e.getMessage() rather than e

2022-07-11 11:04 UTC, ConorGallagher1 approved these changes

2022-07-11 11:24 UTC, merged